<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;

#[Route('/api/auth')]
class AuthController extends AbstractController
{
    #[Route('/login', methods: ['POST'])]
    public function login(#[CurrentUser] ?User $user): JsonResponse
    {
        if (null === $user) {
            return $this->json([
                'message' => 'Invalid credentials',
            ], Response::HTTP_UNAUTHORIZED);
        }

        // JWT token is generated by JsonLoginAuthenticator
        // This endpoint is handled entirely by the security authenticator
        return $this->json([
            'message' => 'Login endpoint',
        ]);
    }

    #[Route('/logout', methods: ['POST'])]
    public function logout(#[CurrentUser] ?User $user): JsonResponse
    {
        // JWT is stateless, so logout is client-side (remove token)
        // Return success response to client
        return $this->json([
            'message' => 'Successfully logged out',
        ], Response::HTTP_OK);
    }
}
